// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Buttler.Domain.Models
{
    public partial class Foods
    {
        public Foods()
        {
            OrderItems = new HashSet<OrderItems>();
        }

        public int FoodsId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FoodImg { get; set; }
        public decimal? Price { get; set; }

        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}