// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Buttler.Domain.Models
{
    public partial class Tables
    {
        public Tables()
        {
            OrderMasters = new HashSet<OrderMasters>();
        }

        public int TablesId { get; set; }
        public int TableNumber { get; set; }
        public int? CustomerId { get; set; }

        public virtual Customers Customer { get; set; }
        public virtual ICollection<OrderMasters> OrderMasters { get; set; }
    }
}